-- Script de remplissage des semestres, unités, cours et TD pour Génie Informatique
-- À exécuter dans votre base SQLite (iut_courses.db)

-- Nettoyage préalable
DELETE FROM courses;
DELETE FROM unites;
DELETE FROM semestres;

-- Semestres
INSERT OR IGNORE INTO semestres (id, nom) VALUES
  (1, 'Semestre 1'),
  (2, 'Semestre 2'),
  (3, 'Semestre 3'),
  (4, 'Semestre 4');

-- Unités d'enseignement (exemple détaillé, à adapter)
INSERT OR IGNORE INTO unites (id, nom, semestre_id, professeur, credits, description) VALUES
  -- Semestre 1
  (1, 'Analyse mathématique et Algèbre linéaire', 1, 'Dr. Tchouankem', 6, 'Analyse mathématique, algèbre linéaire et applications.'),
  (2, 'Langues, Communication', 1, 'Mme. Nguimfack', 3, 'Langues étrangères et communication professionnelle.'),
  (3, 'Matériel, Logiciels, Réseaux', 1, 'M. Fotsing', 4, 'Découverte du matériel informatique, systèmes et réseaux.'),
  (4, 'Algorithmique et Programmation', 1, 'Dr. Kamga', 5, 'Bases de l’algorithmique et de la programmation.'),
  (5, 'Traitement de l’Information', 1, 'Dr. Nguimfack', 3, 'Traitement et organisation de l’information.'),
  (6, 'Physique générale et Mécanique', 1, 'Dr. Tchouankem', 3, 'Physique appliquée à l’informatique.'),
  -- Semestre 2
  (7, 'Comptabilité et Relations', 2, 'Mme. Nguimfack', 3, 'Comptabilité et relations professionnelles.'),
  (8, 'Droit et Ethique', 2, 'M. Fotsing', 2, 'Droit de l’informatique et éthique.'),
  (9, 'Réseaux, Introduction à l’IoT', 2, 'Dr. Kamga', 4, 'Réseaux informatiques et introduction à l’IoT.'),
  (10, 'Architecture d’ordinateurs', 2, 'Dr. Tchouankem', 4, 'Architecture matérielle des ordinateurs.'),
  (11, 'Programmation et Bases de Données', 2, 'Dr. Nguimfack', 5, 'Programmation avancée et bases de données.'),
  (12, 'Mathématiques discrètes', 2, 'Dr. Tchouankem', 3, 'Logique, ensembles, graphes, combinatoire.'),
  -- Semestre 3
  (13, 'Probabilités, Statistiques et Analyse numerique', 3, 'Dr. Kamga', 6, 'Probabilités et statistiques pour l’informatique.'),
  (14, 'Langues et Communication', 3, 'Pr Tanguy', 4, 'Technique de communication 2 e Anglais 2.'),
  (15, 'Modélisation et Programmation orientée objets', 3, 'Pr Tayou, Dr Fotsing Eric', 5, 'Modélisation (UML), ET Progammation Java'),
  (16, 'Développement Web et Client-Serveur', 3, 'Pr Noulamo Thierry, Dr Kemogne Belise', 4, 'Développement web et applications client-serveur.'),
  (17, 'Système d’exploitation et Télécommunications / Routage / Base Télécom /  Electronique numérique (ISR)', 3, 'Dr. Kamga', 11, 'Systèmes d’exploitation et réseaux avancés.'),
  (18, 'Système d’exploitation et Ingénierie de logiciels / Systèmes d’information 2 / Bases de données2  (GL)', 3, 'Dr. Nguimfack', 11, 'Projet d’application ou de recherche.'),
  -- Semestre 4
  (19, 'Applications mobiles', 4, 'Dr. Nguimfack', 4, 'Développement d’applications mobiles.'),
  (20, 'Entrepreneuriat, Gestion', 4, 'Mme. Nguimfack', 3, 'Entrepreneuriat et gestion de projet.'),
  (21, 'Développement Multimédia', 4, 'M. Fotsing', 4, 'Développement multimédia et design.'),
  (22, 'Réseaux à grande échelle', 4, 'Dr. Kamga', 4, 'Réseaux informatiques à grande échelle.'),
  (23, 'Synthèse de Projet', 4, 'Dr. Tchouankem', 6, 'Projet de synthèse de fin de cycle.'),
  (24, 'Stage professionnel', 4, 'Dr. Nguimfack', 6, 'Stage en entreprise ou laboratoire.');

-- Cours et TD (exemple pour quelques unités, à compléter selon référentiel)
DELETE FROM courses;
INSERT OR IGNORE INTO courses (nom, unite_id, type) VALUES
  -- UE 1
  ('Analyse Mathématique (AMN1111)', 1, 'cours'),
  ('Algèbre Linéaire (ALL1112)', 1, 'cours'),
  ('TD 1 : Suites et séries', 1, 'td'),
  ('TD 2 : Espaces vectoriels', 1, 'td'),
  -- UE 2
  ('Anglais Technique', 2, 'cours'),
  ('Communication Orale', 2, 'cours'),
  ('TD 1 : Présentations', 2, 'td'),
  ('TD 2 : Rédaction', 2, 'td'),
  -- UE 3 à 24 : valeurs par défaut si non connues
  ('Cours principal', 3, 'cours'),
  ('Cours complémentaire', 3, 'cours'),
  ('TD 1', 3, 'td'),
  ('TD 2', 3, 'td'),
  ('Cours principal', 4, 'cours'),
  ('Cours complémentaire', 4, 'cours'),
  ('TD 1', 4, 'td'),
  ('TD 2', 4, 'td'),
  ('Cours principal', 5, 'cours'),
  ('Cours complémentaire', 5, 'cours'),
  ('TD 1', 5, 'td'),
  ('TD 2', 5, 'td'),
  ('Cours principal', 6, 'cours'),
  ('Cours complémentaire', 6, 'cours'),
  ('TD 1', 6, 'td'),
  ('TD 2', 6, 'td'),
  ('Cours principal', 7, 'cours'),
  ('Cours complémentaire', 7, 'cours'),
  ('TD 1', 7, 'td'),
  ('TD 2', 7, 'td'),
  ('Cours principal', 8, 'cours'),
  ('Cours complémentaire', 8, 'cours'),
  ('TD 1', 8, 'td'),
  ('TD 2', 8, 'td'),
  ('Cours principal', 9, 'cours'),
  ('Cours complémentaire', 9, 'cours'),
  ('TD 1', 9, 'td'),
  ('TD 2', 9, 'td'),
  ('Cours principal', 10, 'cours'),
  ('Cours complémentaire', 10, 'cours'),
  ('TD 1', 10, 'td'),
  ('TD 2', 10, 'td'),
  ('Cours principal', 11, 'cours'),
  ('Cours complémentaire', 11, 'cours'),
  ('TD 1', 11, 'td'),
  ('TD 2', 11, 'td'),
  ('Cours principal', 12, 'cours'),
  ('Cours complémentaire', 12, 'cours'),
  ('TD 1', 12, 'td'),
  ('TD 2', 12, 'td'),
  ('Cours principal', 13, 'cours'),
  ('Cours complémentaire', 13, 'cours'),
  ('TD 1', 13, 'td'),
  ('TD 2', 13, 'td'),
  ('Cours principal', 14, 'cours'),
  ('Cours complémentaire', 14, 'cours'),
  ('TD 1', 14, 'td'),
  ('TD 2', 14, 'td'),
  ('Cours principal', 15, 'cours'),
  ('Cours complémentaire', 15, 'cours'),
  ('TD 1', 15, 'td'),
  ('TD 2', 15, 'td'),
  ('Cours principal', 16, 'cours'),
  ('Cours complémentaire', 16, 'cours'),
  ('TD 1', 16, 'td'),
  ('TD 2', 16, 'td'),
  ('Cours principal', 17, 'cours'),
  ('Cours complémentaire', 17, 'cours'),
  ('TD 1', 17, 'td'),
  ('TD 2', 17, 'td'),
  ('Cours principal', 18, 'cours'),
  ('Cours complémentaire', 18, 'cours'),
  ('TD 1', 18, 'td'),
  ('TD 2', 18, 'td'),
  ('Cours principal', 19, 'cours'),
  ('Cours complémentaire', 19, 'cours'),
  ('TD 1', 19, 'td'),
  ('TD 2', 19, 'td'),
  ('Cours principal', 20, 'cours'),
  ('Cours complémentaire', 20, 'cours'),
  ('TD 1', 20, 'td'),
  ('TD 2', 20, 'td'),
  ('Cours principal', 21, 'cours'),
  ('Cours complémentaire', 21, 'cours'),
  ('TD 1', 21, 'td'),
  ('TD 2', 21, 'td'),
  ('Cours principal', 22, 'cours'),
  ('Cours complémentaire', 22, 'cours'),
  ('TD 1', 22, 'td'),
  ('TD 2', 22, 'td'),
  ('Cours principal', 23, 'cours'),
  ('Cours complémentaire', 23, 'cours'),
  ('TD 1', 23, 'td'),
  ('TD 2', 23, 'td'),
  ('Cours principal', 24, 'cours'),
  ('Cours complémentaire', 24, 'cours'),
  ('TD 1', 24, 'td'),
  ('TD 2', 24, 'td');
-- Toutes les UE ont maintenant des cours et TD par défaut
